# Generated by Django 5.2.12 on 2026-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phoneNumber', models.IntegerField(max_length=50)),
                ('date', models.DateField()),
                ('typeOfPollution', models.CharField(max_length=150)),
                ('detailDescription', models.TextField()),
            ],
        ),
    ]
