# Generated by Django 6.0.3 on 2026-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='phoneNumber',
            field=models.IntegerField(max_length=15),
        ),
    ]
